apiVersion: v1
kind: Secret
metadata:
  name: db-password
data:
  password: WU9VUl9QQVNTV09SRA==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgres
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - image: arm64v8/postgres:14.2
        name: postgres
        env:
        - name: PGDATA 
          value: "/var/lib/postgresql/data/pgdata" 
        - name: POSTGRES_PASSWORD 
          valueFrom: 
             secretKeyRef: 
                name: db-password 
                key: password
        ports:
        - containerPort: 5432
        resources:
          limits:
            cpu: "0.5"
            memory: "200Mi"
        volumeMounts:
        - mountPath: "/var/lib/postgresql/data"
          name: postgres-storage
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: db-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
  name: postgres
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgres
  type: ClusterIP