apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: metrics
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: metrics
  type: LoadBalancer
status:
  loadBalancer: {}