apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: mysql-lb
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql
  type: LoadBalancer
status:
  loadBalancer: {}