hostname: master
ssh_authorized_keys:
- ssh-rsa YOUR_KEY
write_files:
  - path: /var/lib/connman/default.config
    content: |-
      [service_eth0]
      Type=ethernet
      IPv4=192.168.0.11/255.255.255.0/192.168.0.1
      IPv6=off
      Nameservers=8.8.8.8
k3os:
  dns_nameservers:
  - 8.8.8.8
  - 1.1.1.1
  ntp_servers:
  - 0.us.pool.ntp.org
  - 1.us.pool.ntp.org
  password: rancher
  labels:
    region: america-central-1 
  k3s_args:
  - server
  - "--write-kubeconfig-mode"
  - "644"
  - "--no-deploy"
  - "traefik"
  - "--disable"
  - "traefik"
