apiVersion: v1
kind: Namespace
metadata:
  name: event-demo
  labels:
       eventing.knative.dev/injection: enabled
---
apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  name: default
  namespace: event-demo
  annotations:
    eventing.knative.dev/broker.class: MTChannelBasedBroker
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-demo
  name: api-demo
  namespace: event-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-demo
  template:
    metadata:
      labels:
        app: api-demo
    spec:
      containers:
      - image: sergioarmgpl/app3demo
        name: app3demo
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-demo
  name: api-demo
  namespace: event-demo
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: api-demo
  type: ClusterIP
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: api-demo
  namespace: event-demo
spec:
  broker: default
  filter:
    attributes:
      type: event.show
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: api-demo