[package]
name = "hello-rust"
version = "0.1.0"
authors = ["Sergio Méndez <sergio.mendez@yalochat.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
