apiVersion: v1
kind: Service
metadata:
  labels:
    app: mosquitto
  name: mosquitto-lb
spec:
  ports:
  - name: mqtt
    port: 1883
    protocol: TCP
    targetPort: 1883
  - name: http
    port: 9001
    protocol: TCP
    targetPort: 9001
  selector:
    app: mosquitto
  type: LoadBalancer
