apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
  namespace: monitoring
data:
  prometheus.yml: |-
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
      external_labels:
        monitor: 'codelab-monitor'
    scrape_configs:
      - job_name: 'MonitoringJob1'
        scrape_interval: 5s
        static_configs:
          - targets: ['service1:5555']
