apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: prometheus-server
  name: prometheus-service
  namespace: monitoring
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 9090
  selector:
    app: prometheus-server
  type: ClusterIP
