apiVersion: v1
kind: Service
metadata:
  labels:
    run: redis
  name: redis
  namespace: monitoring
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    run: redis
  type: ClusterIP
