apiVersion: v1
kind: Service
metadata:
  labels:
    app: service1
  name: service1
  namespace: monitoring
spec:
  ports:
  - port: 5555
    protocol: TCP
    targetPort: 5555
  selector:
    app: service1
  type: ClusterIP
